language: node_js
node_js:
- '14.15.4'

cache:
  directories:
    - "node_modules"

script:
  - yarn run build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  committer-from-gh: true
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  repo: loader
  target-branch: main
  on:
    branch: gh-pages